Fix version name can be empty string
modrinth/labrinth pull request #537
Opened 2023-02-12 10:49 UTC by MagnusHJensen

**Description:**
Validates the version name, to check if trimming the name results in the string being empty.
Also trims the name on insert, to remove whitespace before and after name.

**Media:**

https://user-images.githubusercontent.com/32039051/218306547-d29a6ef7-9211-401c-bc9c-8e4c83617a1f.mov

Closes: #169

2023-02-13 12:48 UTC, MagnusHJensen commented
The same validation should now run on project/version creation, and project/version editing.

2023-02-13 14:31 UTC, triphora requested changes

2023-02-13 14:31 UTC, triphora commented on src/routes/version_creation.rs
> +                println!("{}", version_create_data.version_title.clone());
Debug line left in
```suggestion

```

2023-02-13 15:14 UTC, MagnusHJensen commented on src/routes/version_creation.rs
> +                println!("{}", version_create_data.version_title.clone());
Fixed

2023-02-13 15:16 UTC, triphora approved these changes

2023-02-15 16:41 UTC, Geometrically requested changes
It looks like this only applies to version editing, not creation

2023-02-15 17:05 UTC, MagnusHJensen commented
It also applies to version creation, and assuming project creation due to no validation/trimming.
Just tested it creating a version with blank name with spaces, and it was allowed.

2023-02-21 22:35 UTC, Geometrically approved these changes

2023-03-03 23:04 UTC, triphora commented on src/util/validate.rs
> +            "Name can not contain only whitespace.",
```suggestion
            "Name cannot contain only whitespace.",
```

2023-03-03 23:20 UTC, merged