WIP: Perses finale
modrinth/labrinth pull request #558
Opened 2023-03-04 16:10 UTC by triphora

Removal of v1, moving of v2, and maybe the start of v3?

Still very WIP and still trying to work out what the scope of this PR is. Making this PR because I much prefer the GitHub diff view over using plain `git diff`.

2023-03-14 21:47 UTC, Geometrically requested changes
looks good besides some minor things. have you tested that the new route registration works?

2023-03-14 21:47 UTC, Geometrically commented on src/routes/mod.rs
> +use actix_web::http::{Method, StatusCode};
unused import `Method`

2023-03-14 21:47 UTC, Geometrically commented on src/routes/mod.rs
> +use chrono::{Timelike, Utc};
unused imports

2023-03-14 22:00 UTC, triphora commented
As far as I can tell it works

2023-03-16 18:55 UTC, Geometrically approved these changes

2023-03-16 18:56 UTC, merged