Add report + moderation messaging
modrinth/labrinth pull request #567
Opened 2023-03-25 01:52 UTC by Geometrically

2023-03-25 04:22 UTC, triphora submitted a review, later dismissed
Is there be a way for moderators to see existing *project* threads (not report threads) that are unresolved? Also, how does opening/closing project threads work?

2023-03-25 04:22 UTC, triphora commented on src/models/threads.rs
> +        }
These need to be updated

2023-03-25 04:22 UTC, triphora commented on src/routes/v2/mod.rs
> +            .configure(threads::config),
Keep the alphabetical order :irritatered:

2023-03-25 04:22 UTC, triphora commented on src/routes/v2/threads.rs
> +#[patch("{id}")]
Seems like this should be a POST route

2023-04-03 16:37 UTC, Prospector requested changes
Thread messages need a way to differentiate anonymous moderator from deleted user or a user that is null for potentially other reasons.

Also, it'd be nice if the project status change message type included the old project status in the message

2023-04-13 00:58 UTC, thesuzerain approved these changes

2023-04-13 00:59 UTC, merged