Minos push (#589)
modrinth/labrinth pull request #590
Opened 2023-05-10 14:18 UTC by thesuzerain

- Adds handling for Minos backend and new authentication system, for simultaneous use with the current version of Minos
- Adds APT generation and use endpoint

Currently incomplete.

Fixes MOD-265
Fixes MOD-399
Fixes MOD-269
Fixes MOD-264
Fixes MOD-269

2023-05-18 23:32 UTC, Geometrically requested changes
this is my old review

2023-05-19 16:05 UTC, thesuzerain commented on src/database/models/ids.rs
> +
Leftover. Was originally going to store a PAT as two base62 encoded i64s as i128 cannot be stored by sqlx. Eventually simple made it a string

2023-05-23 21:12 UTC, Geometrically requested changes

2023-05-25 19:36 UTC, Geometrically requested changes

2023-05-25 19:36 UTC, Geometrically commented on src/routes/v2/admin.rs
> +use crate::{models, DownloadQueue};
clippy

2023-05-25 19:36 UTC, Geometrically commented on src/routes/v2/admin.rs
> +}
print statements

2023-05-25 19:36 UTC, Geometrically commented on src/routes/v2/admin.rs
> +}
also why is there a transaction for get legacy account? can't it just use the pool directly

2023-05-25 19:36 UTC, Geometrically commented on src/util/auth.rs
> +                .ok_or_else(|| AuthenticationError::InvalidCredentials)?;
instead of throwing errors when each auth method fails, shouldn't it try the next one?

2023-05-25 20:12 UTC, thesuzerain commented on src/util/auth.rs
> +        // Tokens beginning with Ory are considered to be Kratos tokens (extracted cookies) and forwarded to Minos
Small unfinished thing I forgot about. Added functionality here, will add matching functionality to Minos after.

2023-05-31 22:41 UTC, Geometrically approved these changes

2023-05-31 23:03 UTC, merged