Version ordering [MOD-551]
modrinth/labrinth pull request #740
Opened 2023-10-28 00:28 UTC by OmegaJak

2023-10-28 00:55 UTC, Geometrically approved these changes

2023-10-28 00:58 UTC, Geometrically requested changes

2023-10-28 00:58 UTC, Geometrically commented on src/routes/v2/versions.rs
make sure to incorporate other routes that rely on ordering, like updating, version slug route, maven, etc

2023-10-30 20:36 UTC, OmegaJak commented on src/routes/v2/versions.rs
Alright, implemented for maven and every other bit of code I could find that was previously sorting by `date_published` in Rust (as opposed to in SQL).

2023-10-31 17:18 UTC, Geometrically approved these changes

2023-11-01 16:36 UTC, merged