Search overhaul
modrinth/labrinth pull request #771
Opened 2023-11-29 03:38 UTC by thesuzerain

- Search return Project struct now matches models Project
Adds all the other relevant data to meilisearch- Im not sure if this will end up being too much.
I tried to keep it as few other changes as possible. 
It DOES remove the body from the model for search models- probably would be too much data!

2023-11-29 18:18 UTC, Geometrically requested changes
Make dynamic fields for project, pass along dynamic field for version

2023-12-01 01:35 UTC, thesuzerain commented
> Make dynamic fields for project, pass along dynamic field for version

did this in the other PR

2023-12-01 19:29 UTC, thesuzerain commented on src/models/v3/projects.rs
> +// TODO: Rethink this a little bit.
This is more of a- could all the version_field stuff be structured better to revisit in the future. Removed the comment for now.

2023-12-03 14:27 UTC, Geometrically approved these changes

2023-12-03 14:27 UTC, merged